export const MOCK_MEAL_DATA = [
  {
    id: 1,
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 2,
    date: "11/2(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 3,
    date: "11/3(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 4,
    date: "11/4(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 5,
    date: "11/5(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 6,
    date: "11/6(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    id: 7,
    date: "11/7(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
]
