export const MOCK_MEAL_DATA = [
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
  {
    date: "11/1(火)",
    breakfast: "飯味噌汁",
    lunch: "ご飯",
    dinner_a: "テキスト",
    dinner_b: "ご飯",
    dinner_c: "パスタサラダ",
    other: "ドーナッツ",
  },
]
