export const MOCK_MEAL_DETAIL_DATA = [
  {
    id: 1,
    menu_name: "ご飯",
    energy: "76 kcal",
    protein: "14.7 g",
    lipid: "0.2 g",
    salt: "0.7 g",
  },
  {
    id: 2,
    menu_name: "味噌汁",
    energy: "49 kcal",
    protein: "3.1 g",
    lipid: "3.3 g",
    salt: "0.4 g",
  },
  {
    id: 3,
    menu_name: "ハムエッグ",
    energy: "21 kcal",
    protein: "1.6 g",
    lipid: "0.1 g",
    salt: "0.7 g",
  },
  {
    id: 4,
    menu_name: "豚汁",
    energy: "50 kcal",
    protein: "3.5 g",
    lipid: "2.4 g",
    salt: "1.3 g",
  },
  {
    id: 5,
    menu_name: "ごはん",
    energy: "394 kcal",
    protein: "6.7 g",
    lipid: "1 g",
    salt: "0.7 g",
  },
  {
    id: 6,
    menu_name: "タラの幽庵焼き",
    energy: "76 kcal",
    protein: "14.7 g",
    lipid: "0.2 g",
    salt: "0.7 g",
  },
  {
    id: 7,
    menu_name: "牛乳",
    energy: "134 kcal",
    protein: "6.6 g",
    lipid: "7.6 g",
    salt: "0.2 g",
  },
]
