export const EXTRA_ACTIVITY_LIST = [
  { key: "baseball_club", label: "extra_activity_list.baseball_club" },
  { key: "rub_baseball_club", label: "extra_activity_list.rub_baseball_club" },
  { key: "american_football_club", label: "extra_activity_list.american_football_club" },
  { key: "soccer_club", label: "extra_activity_list.soccer_club" },
  { key: "table_tennis_club", label: "extra_activity_list.table_tennis_club" },
  { key: "badminton_club", label: "extra_activity_list.badminton_club" },
  { key: "basket_club", label: "extra_activity_list.basket_club" },
  { key: "music_club", label: "extra_activity_list.music_club" },
  { key: "science_depart", label: "extra_activity_list.science_depart" },
  { key: "maths_depart", label: "extra_activity_list.maths_depart" },
  { key: "shogi_club", label: "extra_activity_list.shogi_club" },
  { key: "broadcast_depart", label: "extra_activity_list.broadcast_depart" },
  { key: "perform_art_depart", label: "extra_activity_list.perform_art_depart" },
  { key: "theater_club", label: "extra_activity_list.theater_club" },
  { key: "academic_club", label: "extra_activity_list.academic_club" },
  { key: "vk_club", label: "extra_activity_list.vk_club" },
  { key: "program_club", label: "extra_activity_list.program_club" },
  { key: "swim_club", label: "extra_activity_list.swim_club" },
  { key: "railway_club", label: "extra_activity_list.railway_club" },
  { key: "model_nation_club", label: "extra_activity_list.model_nation_club" },
  { key: "art_club", label: "extra_activity_list.art_club" },
]
