export const MOCK_APPLICATION_DATA = [
  {
    id: 1,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "外出",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 2,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "テキスト",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 3,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "欠席",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 4,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 5,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 6,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 7,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 8,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 9,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 10,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 11,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 12,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 13,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
  {
    id: 14,
    student: "田中花子",
    hm: "テキスト",
    applicationtime: "テキスト",
    leavetime: "テキスト",
    returntime: "テキスト",
    category: "帰寮帰宅",
    reason: "テキスト",
    approval: "承認済み",
  },
]
