name: linter
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn eslint --fix
      - name: TS Compile
        run: yarn tsc --noEmit
